name: Action Testing
on: workflow_dispatch
jobs:
  test-some-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Output directory contents
        run: ls -la
      - name: Replace tokens in relevant k8s yamls
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: '["./config.json"]'
      
      - name: Read file contents
        id: configFile
        uses: andstor/file-reader-action@v1
        with:
          path: "config.json"

      - name: config.json contents
        run: echo "${ steps.configFile.outputs.contents }"
