name: Action Testing
on: workflow_dispatch
jobs:
  test-some-actions:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Replace tokens
        uses: qetza/replacetokens-action@v1
        with:
          sources: ./config.json
          token-pattern: 'custom'
          token-prefix: '#{'
          token-suffix: '}'
          variables: '[${{ toJSON(vars) }},${{ toJSON(secrets) }}]' # use all env variables & secrets
          
      - name:  Read config.json file
        id: configFile
        uses: jaywcjlove/github-action-read-file@main
        with:
          localfile: ./config.json

      - name: Echo config.json
        run: echo "${{ steps.configFile.outputs.content }}"
