name: Action Testing
on: workflow_dispatch
jobs:
  test-some-actions:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ vars.API_URL }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Output directory contents
        run: ls -la
      - name: Replace tokens in relevant k8s yamls
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}'
          files: '["./config.json"]'
          
      - name:  Read config.json file
        id: configFile
        uses: jaywcjlove/github-action-read-file@main
        with:
          localfile: ./config.json

      - name: Echo config.json
        run: echo "${{ steps.configFile.outputs.content }}"
